prob5-rot1-sp3:
	npm run meta -- --problemId 5 --batchName shift-test-rot1-sp3 --command '../../kawatea/a.out' --rotate 1 --split 3

prob5-rot1-sp4:
	npm run meta -- --problemId 5 --batchName shift-test-rot1-sp4 --command '../../kawatea/a.out' --rotate 1 --split 4

prob5-rot3-sp3:
	npm run meta -- --problemId 5 --batchName shift-test-rot3-sp3 --command '../../kawatea/a.out' --rotate 3 --split 3

prob5-rot3-sp4:
	npm run meta -- --problemId 5 --batchName shift-test-rot3-sp4 --command '../../kawatea/a.out' --rotate 3 --split 4

prob8-rot1-sp4:
	npm run meta -- --problemId 8 --batchName shift-test-rot1-sp4 --command '../../kawatea/a.out' --rotate 1 --split 4

prob7-rot1-sp4:
	npm run meta -- --problemId 7 --batchName shift-test-rot1-sp4 --command '../../kawatea/a.out' --rotate 1 --split 4

prob7-rot1-sp5:
	npm run meta -- --problemId 7 --batchName shift-test-rot1-sp5 --command '../../kawatea/a.out' --rotate 1 --split 5

prob7-rot3-sp4:
	npm run meta -- --problemId 7 --batchName shift-test-rot3-sp4 --command '../../kawatea/a.out' --rotate 3 --split 4

prob7-rot3-sp5:
	npm run meta -- --problemId 7 --batchName shift-test-rot3-sp5 --command '../../kawatea/a.out' --rotate 3 --split 5

prob9-rot0-sp3:
	npm run meta -- --problemId 9 --batchName shift-test-rot0-sp3 --command '../../kawatea/a.out' --rotate 0 --split 3

prob9-rot0-sp4:
	npm run meta -- --problemId 9 --batchName shift-test-rot0-sp4 --command '../../kawatea/a.out' --rotate 0 --split 4

prob12-rot0-sp4:
	npm run meta -- --problemId 12 --batchName shift-test-rot0-sp4 --command '../../kawatea/a.out' --rotate 0 --split 4

prob12-rot0-sp5:
	npm run meta -- --problemId 12 --batchName shift-test-rot0-sp5 --command '../../kawatea/a.out' --rotate 0 --split 5

prob12-rot2-sp4:
	npm run meta -- --problemId 12 --batchName shift-test-rot2-sp4 --command '../../kawatea/a.out' --rotate 2 --split 4

prob12-rot2-sp5:
	npm run meta -- --problemId 12 --batchName shift-test-rot2-sp5 --command '../../kawatea/a.out' --rotate 2 --split 5

prob15-rot0-sp4:
	npm run meta -- --problemId 15 --batchName shift-test-rot0-sp4 --command '../../kawatea/a.out' --rotate 0 --split 4

prob15-rot2-sp4:
	npm run meta -- --problemId 15 --batchName shift-test-rot2-sp4 --command '../../kawatea/a.out' --rotate 2 --split 4

prob20-rot1-sp3:
	npm run meta -- --problemId 20 --batchName shift-test-rot1-sp3 --command '../../kawatea/a.out' --rotate 1 --split 3

prob20-rot1-sp4:
	npm run meta -- --problemId 20 --batchName shift-test-rot1-sp4 --command '../../kawatea/a.out' --rotate 1 --split 4

prob20-rot1-sp5:
	npm run meta -- --problemId 20 --batchName shift-test-rot1-sp5 --command '../../kawatea/a.out' --rotate 1 --split 5

prob20-rot2-sp3:
	npm run meta -- --problemId 20 --batchName shift-test-rot2-sp3 --command '../../kawatea/a.out' --rotate 2 --split 3

prob20-rot2-sp4:
	npm run meta -- --problemId 20 --batchName shift-test-rot2-sp4 --command '../../kawatea/a.out' --rotate 2 --split 4

prob20-rot2-sp5:
	npm run meta -- --problemId 20 --batchName shift-test-rot2-sp5 --command '../../kawatea/a.out' --rotate 2 --split 5

prob20-rot3-sp3:
	npm run meta -- --problemId 20 --batchName shift-test-rot3-sp3 --command '../../kawatea/a.out' --rotate 3 --split 3

prob20-rot3-sp4:
	npm run meta -- --problemId 20 --batchName shift-test-rot3-sp4 --command '../../kawatea/a.out' --rotate 3 --split 4

prob20-rot3-sp5:
	npm run meta -- --problemId 20 --batchName shift-test-rot3-sp5 --command '../../kawatea/a.out' --rotate 3 --split 5

prob24-rot0-sp4:
	npm run meta -- --problemId 24 --batchName shift-test-rot0-sp4 --command '../../kawatea/a.out' --rotate 0 --split 4

prob24-rot0-sp5:
	npm run meta -- --problemId 24 --batchName shift-test-rot0-sp5 --command '../../kawatea/a.out' --rotate 0 --split 5

prob24-rot1-sp4:
	npm run meta -- --problemId 24 --batchName shift-test-rot1-sp4 --command '../../kawatea/a.out' --rotate 1 --split 4

prob24-rot1-sp5:
	npm run meta -- --problemId 24 --batchName shift-test-rot1-sp5 --command '../../kawatea/a.out' --rotate 1 --split 5

prob24-rot2-sp4:
	npm run meta -- --problemId 24 --batchName shift-test-rot2-sp4 --command '../../kawatea/a.out' --rotate 2 --split 4

prob24-rot2-sp5:
	npm run meta -- --problemId 24 --batchName shift-test-rot2-sp5 --command '../../kawatea/a.out' --rotate 2 --split 5

prob24-rot3-sp4:
	npm run meta -- --problemId 24 --batchName shift-test-rot3-sp4 --command '../../kawatea/a.out' --rotate 3 --split 4

prob24-rot3-sp5:
	npm run meta -- --problemId 24 --batchName shift-test-rot3-sp5 --command '../../kawatea/a.out' --rotate 3 --split 5

all: prob5-rot1-sp3 prob5-rot1-sp4 prob5-rot3-sp3 prob5-rot3-sp4 prob8-rot1-sp4 prob7-rot1-sp4 prob7-rot1-sp5 prob7-rot3-sp4 prob7-rot3-sp5 prob9-rot0-sp3 prob9-rot0-sp4 prob12-rot0-sp4 prob12-rot0-sp5 prob12-rot2-sp4 prob12-rot2-sp5 prob15-rot0-sp4 prob15-rot2-sp4 prob20-rot1-sp3 prob20-rot1-sp4 prob20-rot1-sp5 prob20-rot2-sp3 prob20-rot2-sp4 prob20-rot2-sp5 prob20-rot3-sp3 prob20-rot3-sp4 prob20-rot3-sp5 prob24-rot0-sp4 prob24-rot0-sp5 prob24-rot1-sp4 prob24-rot1-sp5 prob24-rot2-sp4 prob24-rot2-sp5 prob24-rot3-sp4 prob24-rot3-sp5
